// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customerModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Customer _$CustomerFromJson(Map<String, dynamic> json) {
  return Customer(
    No_: json['No_'] as String,
    Name: json['Name'] as String,
    Address: json['Address'] as String,
    blocked: json['blocked'] as int,
    limit: json['limit'] as String,
    disc: json['disc'] as String,
    limit_dmd: json['limit_dmd'] as int,
    pembayaranc1: json['pembayaranc1'] as int,
    pembayaranc2: json['pembayaranc2'] as int,
    pembayaranc3: json['pembayaranc3'] as int,
    pembayaranc4: json['pembayaranc4'] as int,
    top_catm: json['top_catm'] as int,
    top_cat: json['top_cat'] as int,
    top_mebelm: json['top_mebelm'] as int,
    top_mebel: json['top_mebel'] as int,
    pembayaranm1: json['pembayaranm1'] as int,
    pembayaranm2: json['pembayaranm2'] as int,
    pembayaranm3: json['pembayaranm3'] as int,
    pembayaranm4: json['pembayaranm4'] as int,
    pembayaranb1: json['pembayaranb1'] as int,
    pembayaranb2: json['pembayaranb2'] as int,
    pembayaranb3: json['pembayaranb3'] as int,
    pembayaranb4: json['pembayaranb4'] as int,
    retur: json['retur'] as int,
    jum: json['jum'] as int,
    piutang: json['piutang'] as int,
    ov: json['ov'] as int,
    document_no: json['document_no'] as String,
    due_date: json['due_date'] as String,
    sisa: json['sisa'] as String,
    PIN: json['PIN'] as String,
    jum_byr: json['jum_byr'] as int,
    pengali: json['pengali'] as int,
    rata2: json['rata2'] as int,
    total_omzet_cat: json['total_omzet_cat'] as int,
    total_omzet_bb: json['total_omzet_bb'] as int,
    total_omzet_mebel: json['total_omzet_mebel'] as int,
  );
}

Map<String, dynamic> _$CustomerToJson(Customer instance) => <String, dynamic>{
      'No_': instance.No_,
      'Name': instance.Name,
      'Address': instance.Address,
      'blocked': instance.blocked,
      'limit': instance.limit,
      'disc': instance.disc,
      'limit_dmd': instance.limit_dmd,
      'pembayaranc1': instance.pembayaranc1,
      'pembayaranc2': instance.pembayaranc2,
      'pembayaranc3': instance.pembayaranc3,
      'pembayaranc4': instance.pembayaranc4,
      'top_catm': instance.top_catm,
      'top_cat': instance.top_cat,
      'top_mebelm': instance.top_mebelm,
      'top_mebel': instance.top_mebel,
      'pembayaranm1': instance.pembayaranm1,
      'pembayaranm2': instance.pembayaranm2,
      'pembayaranm3': instance.pembayaranm3,
      'pembayaranm4': instance.pembayaranm4,
      'pembayaranb1': instance.pembayaranb1,
      'pembayaranb2': instance.pembayaranb2,
      'pembayaranb3': instance.pembayaranb3,
      'pembayaranb4': instance.pembayaranb4,
      'retur': instance.retur,
      'jum': instance.jum,
      'piutang': instance.piutang,
      'ov': instance.ov,
      'document_no': instance.document_no,
      'due_date': instance.due_date,
      'sisa': instance.sisa,
      'PIN': instance.PIN,
      'jum_byr': instance.jum_byr,
      'pengali': instance.pengali,
      'rata2': instance.rata2,
      'total_omzet_cat': instance.total_omzet_cat,
      'total_omzet_bb': instance.total_omzet_bb,
      'total_omzet_mebel': instance.total_omzet_mebel,
    };
